# Generated by Django 6.0.2 on 2026-02-13 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('pedidos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, verbose_name='fecha de venta')),
                ('items_snapshot', models.JSONField(blank=True, default=list, help_text='Detalle de productos al momento de la venta.', verbose_name='snapshot de items')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='venta', to='pedidos.pedido', verbose_name='pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=300, verbose_name='nombre del producto')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU')),
                ('cantidad', models.PositiveIntegerField(verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_venta', to='inventario.producto', verbose_name='producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.venta', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'item de venta',
                'verbose_name_plural': 'items de venta',
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['usuario'], name='ventas_vent_usuario_18c0be_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_venta'], name='ventas_vent_fecha_v_357f1c_idx'),
        ),
    ]
