# Generated by Django 6.0.2 on 2026-02-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='correo electrónico')),
                ('telefono', models.CharField(blank=True, default='', max_length=20, verbose_name='teléfono')),
                ('asunto', models.CharField(max_length=300, verbose_name='asunto')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('leido', models.BooleanField(default=False, verbose_name='leído')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuscripcionNewsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de suscripción')),
            ],
            options={
                'verbose_name': 'suscripción newsletter',
                'verbose_name_plural': 'suscripciones newsletter',
                'ordering': ['-created_at'],
            },
        ),
    ]
