# Generated by Django 6.0.2 on 2026-02-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcionnewsletter',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nombre'),
        ),
    ]
