# Generated by Django 6.0.2 on 2026-02-13 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mercadopago_preference_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='MP preference ID')),
                ('mercadopago_payment_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='MP payment ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('estado_detalle', models.CharField(blank=True, default='', max_length=255, verbose_name='detalle del estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto')),
                ('metodo', models.CharField(blank=True, default='', max_length=50, verbose_name='método de pago')),
                ('raw_response', models.JSONField(blank=True, default=dict, verbose_name='respuesta cruda MP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='pedidos.pedido', verbose_name='pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mercadopago_preference_id'], name='pagos_pago_mercado_3fd492_idx'), models.Index(fields=['mercadopago_payment_id'], name='pagos_pago_mercado_8d3f5d_idx'), models.Index(fields=['estado'], name='pagos_pago_estado_c1c831_idx')],
            },
        ),
    ]
