# Generated by Django 6.0.2 on 2026-02-20 18:04

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje'), ('monto_fijo', 'Monto Fijo')], default='porcentaje', max_length=20, verbose_name='tipo de descuento')),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor del descuento')),
                ('minimo_compra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='mínimo de compra')),
                ('maximo_usos', models.IntegerField(blank=True, help_text='Dejar en blanco para usos ilimitados.', null=True, verbose_name='máximo de usos')),
                ('usos_actuales', models.IntegerField(default=0, verbose_name='usos actuales')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='fecha de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'cupón',
                'verbose_name_plural': 'cupones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CuponUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='descuento aplicado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de uso')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='descuentos.cupon', verbose_name='cupón')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupon_uso', to='pedidos.pedido', verbose_name='pedido')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupones_usados', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'uso de cupón',
                'verbose_name_plural': 'usos de cupón',
                'ordering': ['-created_at'],
            },
        ),
    ]
