# Generated by Django 6.0.2 on 2026-02-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('direccion_envio', models.CharField(max_length=255, verbose_name='dirección de envío')),
                ('ciudad', models.CharField(max_length=100, verbose_name='ciudad')),
                ('estado_envio', models.CharField(max_length=100, verbose_name='estado (envío)')),
                ('codigo_postal', models.CharField(max_length=10, verbose_name='código postal')),
                ('metodo_pago', models.CharField(blank=True, default='', max_length=50, verbose_name='método de pago')),
                ('mercadopago_payment_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Mercado Pago payment ID')),
                ('notas', models.TextField(blank=True, default='', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_pedido', to='inventario.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'item de pedido',
                'verbose_name_plural': 'items de pedido',
            },
        ),
    ]
