# Generated by Django 6.0.2 on 2026-02-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuentos', '0001_initial'),
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='descuentos.cupon', verbose_name='cupón'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='monto de descuento'),
        ),
    ]
