# Generated by Django 6.0.2 on 2026-02-23 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_cupon_pedido_descuento_monto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='guest_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email (invitado)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guest_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='nombre (invitado)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guest_telefono',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='teléfono (invitado)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
