# Generated by Django 6.0.2 on 2026-02-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio de oferta')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='imagen principal')),
                ('imagenes', models.JSONField(blank=True, default=list, help_text='Lista de URLs de imágenes adicionales.', verbose_name='imágenes adicionales')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('destacado', models.BooleanField(default=False, verbose_name='destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='inventario.categoria', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='inventario__slug_1cbdbd_idx'), models.Index(fields=['sku'], name='inventario__sku_814480_idx'), models.Index(fields=['activo', 'destacado'], name='inventario__activo_b14b60_idx'), models.Index(fields=['categoria', 'activo'], name='inventario__categor_c6db1b_idx')],
            },
        ),
    ]
