# Generated by Django 6.0.2 on 2026-02-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='imagen principal'),
        ),
    ]
