# Generated by Django 6.0.2 on 2026-02-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_categoria_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='detalles_tecnicos',
            field=models.JSONField(blank=True, default=dict, help_text='Detalles técnicos. Ej: {"switch": "E27", "voltaje": "220-240V"}', verbose_name='detalles técnicos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='dimensiones',
            field=models.JSONField(blank=True, default=dict, help_text='Dimensiones del producto. Ej: {"alto": "31.7 cm", "diámetro": "25.4 cm"}', verbose_name='dimensiones'),
        ),
        migrations.AddField(
            model_name='producto',
            name='materiales',
            field=models.JSONField(blank=True, default=list, help_text='Lista de materiales. Ej: ["Polímero biodegradable", "Acero inoxidable"]', verbose_name='materiales'),
        ),
    ]
